### PR TITLE
Added Event Data 

### PR DESCRIPTION
**Pull request by CalJaDav**
I have added some data that gets packaged with each event, it is still somewhat incomplete, but provides a major upgrade in terms of how external code can interact with tksheet. Each event now broadcasts the name of the widget that broadcasts it (which can now be set as an optional property of `Sheet`), this is so users can identify and retrieve what sheet broadcast the event in cases where they are working with multiple active sheets. `<<SheetModified>>` events also contain an `action` field that details what user action triggered the event, and three other fields (`modified`, `added` and `deleted`, which contain some information about how the data has been changed, more on this later. `<<SheetRedrawn>>` events now contain information about whether the table, headers, or indexes have been redrawn for minor performance improvements in rare cases where the user is attaching significant numbers of elements to their sheet. 

### A Brief Explanation of tkinter Widget Names. 
In tkinter, each widget stores a kind of relative path to its children that can be used to retrieve the objects. Its a really useful feature when you have a lot of widgets going on and events to organise. Each widget has a name, which can be anything you like. In the demo attached, we have a sheet (named `"foo"`) sitting in a frame (name is `"!frame"` by default). We can retrieve this widget by calling `app.nametowidget("!frame.foo")`. This allows users to define unique names for each sheet widget so that event listeners only have to act on the sheet that was actually modified.

### How the modified data parameters work

The way I have currently implemented the data that come package with `<<SheetModified>>` events are quite simple and perhaps might be expanded, but I'll briefly justify my implementation and how I intend it to be used. In my mind, `<<SheetModified>>` listeners are typically going to be processes outside of the sheet that a developer wants to be automatically run every time the user alters a sheet. At least, this is what I have been using them for. The issue is that external code is kind of blind to what is actually happening between changes, and I found myself writing a lot of code just to check for changes that the sheet already knew it was making. This is pretty redundant and can impact performance when you have to check a massive sheet for one changed cell every time a user makes a change. As they are currently implemented, the data that is packaged inside the `<<SheetModified>>` data is designed to tell external code what cells/rows/columns were actually changed. I'll list the fields and subfields, with the rules for each:

`"modified":`
This tells external code what areas of the sheet have been affected by a change. These MUST only refer to VALID sheet data after the change. i.e. if a column at the end of a sheet is deleted, then it must not appear here because if external code tried to retrieve data from it, it will get an error. If a row is removed from the middle of the table, then each proceeding row will count as modified.
 - `"cells"` (`list[tuple]`) A list of changed table cells.
 - `"cols"` (`list[int]`) A list of changed columns, only appears when a header or the whole column is changed (typically when columns are appended or moved around the table). This basically tells the code it check every value in this column for changes/
 - `"rows"` (`list[int]`) See `"cols"` above.

`"deleted":` and `"added":`
This only has rows and columns, as it is impossible to remove individual cells from the table. These are intended to inform external code about changes to the shape of the table. Note that this is only for right-click delete row/column events. Delete-key events are just considered modifications because the don't alter the underlying shape of the data. 
 - `"cols"`, `"rows"`

`"moved"` (Not yet implemented, will get to this tomorrow):
Haven't implemented this yet but it will probably take the following format:
 - `"cols"`, `"rows"` (`list[tuple]`) a list of tuples in the form ("from index", "to index"). 

Below is a small demo to see how this all works. Let me know if you think I'm barking up the right tree here. 
Cheers!
C.

### Demo

```
from tksheet import Sheet
import tkinter as tk

class demo(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.frame = tk.Frame(self)
        self.sheet = Sheet(self.frame, name = 'foo')
        self.sheet.enable_bindings()
        self.frame.pack(expand=True, fill='both')
        self.sheet.pack(expand=True, fill='both')
        self.sheet.set_sheet_data([[None, None, None],['e',1, None]])
        # self.sheet.CH.auto_set_header_height() # New function
        self.sheet.RI
        # self.bind("<<SheetModified>>", self.print_stuff)
        Sheet.bind_event(self, "<<SheetModified>>", self.print_stuff)
        print(self.nametowidget(".!frame.foo").__repr__()) # How names work in tkinter

    def print_stuff(self, e):
        print(e.data)
        
app = demo()
app.mainloop()


```

### CODE REVIEW

**Comment by ragardner** [comment]
Thanks very much for all this, I had just started writing an inferior version when you posted this so your timing was good :P

don't write any docs yet as my changes will likely differ somewhat, you'll have access to even more data as a result but probably a few more lines of code on your end to make use of it

I'll include all the other stuff in this PR too

If you want you can target the PR to the branch event-data and I'll merge it there

**Comment by CalJaDav** [comment]
Added some movement logic/data for events. Currently this only works for inserting/deleting concurrent rows/columns. I will need to update it with more complex logic when deleting non-concurrent items are added to tksheet.

**Comment by ragardner** [comment]
Heads up, I have settled on an event object consistent for all events and internal use as well, I still have to add/change some bits in the docs and test stuff some more but this is what it looks like

https://github.com/ragardner/tksheet/blob/drop-3.6/DOCUMENTATION.md#event-data
https://github.com/ragardner/tksheet/blob/drop-3.6/DOCUMENTATION.md#sheet-modified-events

It has meant that I've been able to add redo functionality as well, not sure how useful that is though

If you need it to be converted to your modified dict and the above isn't clear enough to do it let me know I'll try to add a conversion function to convert the event dict into the dict from this PR

**Comment by CalJaDav** [comment]
This is perfect, thanks! I'll let you know if I bump into any issues when I integrate it into my codebase in a few days. I'll also make some of the refactoring changes we discussed in PR #176.

**Pull request merged**
