### PR TITLE
Cell Formatting 2

### PR DESCRIPTION
**Pull request by CalJaDav**
Here are the cell formatters without the dependencies. I have added a few ways for users to make and customize the cell formatting, see code attached. Let me know what you think. 

```
from tksheet import *
from tksheet.formatters import *
import tkinter as tk
from datetime import datetime, date, timedelta, time
from dateutil import parser, tz
from math import ceil


# --------------------- Special formatter arguements ---------------------
def round_up(x):
    return float(ceil(x))

def only_numeric(s):
    return ''.join([n for n in s if n.isnumeric() or n == '.'])

def convert_to_local_datetime(dt: str):
    if isinstance(dt, datetime):
        pass
    elif isinstance(dt, date):
        dt = datetime(dt.year, dt.month, dt.day)
    elif isinstance(dt, str):
        try:
            dt = parser.parse(dt)
        except Exception as ex:
            raise ValueError(f'Cannot map "{dt}" to datetime.')
    else:
        raise ValueError(f'Cannot map "{dt}" to datetime.')
    if dt.tzinfo is None:
        dt.replace(tzinfo=tz.tzlocal())
    dt = dt.astimezone(tz.tzlocal())
    return dt.replace(tzinfo=None)

def datetime_to_string(dt: datetime):
    return dt.strftime('%d %b, %Y, %H:%M:%S')

# --------------------- Custom Formatter Class ---------------------
class CustomDatetimeFormatter(AbstractFormatterClass):
    def __init__(self, 
                 value, 
                 format = "%d/%m/%Y %H:%M:%S", #Additional arguement that can be passed through the formatter kwargs
                 nullable = True,
                 missing_values = 'NaT',
                 converter = convert_to_local_datetime,
                 pre_conversion_func = None,
                 post_conversion_func = None,
                 ):
        self.format = format
        super().__init__(value, 
                         datetime, 
                         converter,
                         nullable,
                         missing_values,
                         pre_conversion_func,
                         post_conversion_func,
                         )

    def __str__(self):
        if (s:=super().__str__()) != None:
            return s
        return self.value.strftime(self.format)
    

class demo(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.grid_columnconfigure(0, weight = 1)
        self.grid_rowconfigure(0, weight = 1)
        self.frame = tk.Frame(self)
        self.frame.grid_columnconfigure(0, weight = 1)
        self.frame.grid_rowconfigure(0, weight = 1)
        self.sheet = Sheet(self.frame,
                           data = [[f"{r}"]*11 for r in range(20)]
                           )
        self.sheet.enable_bindings()
        self.frame.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.headers(['Non-Nullable Float Cell\n1 decimals places', 
                            'Float Cell', 
                            'Int Cell', 
                            'Bool Cell', 
                            'Percentage Cell\n0 decimal places', 
                            'Custom Datetime Cell',
                            'Custom Datetime Cell Class',
                            'Float Cell that\nrounds up', 
                            'Float cell that\n strips non-numeric', 
                            'Dropdown Over Nullable\nPercentage Cell', 
                            'Checkboxes always\noverride formatting'])
        
        # ---------- Some examples of cell formatting --------
        self.sheet.format_cells('all', 0, FloatFormatter, dict(decimals=1, nullable=False))  
        self.sheet.format_cells('all', 1, FloatFormatter, dict(decimals=5))
        self.sheet.format_cells('all', 2, IntFormatter)
        self.sheet.format_cells('all', 3, BoolFormatter)
        self.sheet.format_cells('all', 4, PercentageFormatter, dict(decimals=0))


        # ---------------- Custom Formatters -----------------
        # Totally custom cell format using the inbuilt cell formatter
        self.sheet.format_cells('all', 5, CellFormatter, dict(datatypes = datetime, 
                                                              converter = convert_to_local_datetime, 
                                                              to_str = datetime_to_string, 
                                                              nullable = False,
                                                              missing_values = 'NaT',
                                                              ))
        # Custom format generated from the base class
        self.sheet.format_cells('all', 6, CustomDatetimeFormatter, dict(format = '%Y-%m-%d %H:%M %p', # Our special extra arguement
                                                                        nullable = True))
        
        # Unique cell behaviour using the post_conversion_function
        self.sheet.format_cells('all', 7, FloatFormatter, dict(post_conversion_func = round_up)) # Custom display format
        self.sheet.format_cells('all', 8, FloatFormatter, dict(pre_conversion_func = only_numeric))

        self.sheet.create_dropdown('all', 9, values=['', '104%',.24,"300%",'not a number'], set_value=1)
        self.sheet.format_cells('all', 9, PercentageFormatter)
        self.sheet.format_cells('all', 10, PercentageFormatter)
        self.sheet.create_checkbox('all', 10, text='Checkbox') # Check boxes always override formatters'''
        # ---------------- retrieving data -------------------
        print(self.sheet.get_sheet_data()) # Default behaviour, returns converted datatypes
        print(self.sheet.get_sheet_data(get_formatters=True)) # Returns the actual MT.data object with formatter objects in place

app = demo()
app.mainloop()

```

### CODE REVIEW

**Comment by ragardner** [comment]
Thanks for the succinct demo, especially the converter functions, I see how the cellformatter class takes the role of a custom formatter

I think the arguments for `format_cells` are simple enough for most anyone to understand what to input, thanks!

Some of the code under the hood I don't have adequate knowledge to understand :(

Does `@abstractmethod` point the `str` function to the child class?

**Comment by CalJaDav** [comment]
Yup, bang on. Think of abstract classes as templates for a family of classes. They can't be instantiated themselves but are designed to provide a framework for a family of inherited classes. Abstract methods must be overridden by child classes. In this case the __str__ method must be overridden because a formatter is obviously designed to provide a custom format for a datatype.

**Comment by CalJaDav** [comment]
I have tidied this up a bit. There are no longer nullable converters, all converters just have a nullable property. I have also tidied up the classes a bit. Nothing major (see updated demo in top comment). Will also look into adding optional copy-paste compatibility for converters.

**Comment by ragardner** [comment]
Sorry for the spam, I'm a bit of a noob with github, I set up a different branch where I could work on the cell formatter stuff while keeping master separate so I could release bug fixes if necessary

**Comment by CalJaDav** [comment]
No problem, I'll pull that branch and send any further requests there.

**Pull request merged**
