### PR TITLE
Feature - Cell Formatting

### PR DESCRIPTION
**Pull request by CalJaDav**
## Motivation
Currently tksheet can store and display any object with a `__str__` method. However, user inputted values from the cell editor are always stored as strings. This patch adds support for cell formatters which aim to bridge this gap.

In this patch, I have added a small library of useful cell formatters and added some additional functionality to the widget to support their use. 

Formatters are essentially a class with a function for parsing a string into another datatype and with a __str__ method to display that data back to the table. The ones I have built come in two basic flavors, nullable and non-nullable. Nullable formatters allow None types to be stored and parsed in addition to their main datatypes. Formatted cells are stored on the `MT.data` inside their formatter class. This means that I have added an additional `get_formatters` argument to the get methods of the Sheet class to allow the user to specify whether they want the converted data returned by the `formatter.data()` method or whether they want the actual formatter object itself. 

Formatting is set using the `Sheet.format_cells` method which functions similar to the `create_dropbox` and `create_checkbox` fucntions. Cell formats are stored as an option on the `MT.cell_options`. Addtitionally, all converters are also stored alongsside of dictionary of additional kwargs that can be parsed to the formatter, allowing for additional customizability (e.g. how many decimal places to display for a float, etc). Formatted cells are fully compatible with dropbox cells, however checkbox cells will always override and delete any cell formatting. Cell formatting can be removed with `Sheet.clear_format` function. I have included some example code to play around with to see how this all works.

Formatters do allow the user to do some cool stuff. For example, the DatetimeCell formatter can parse a wide variety of time-like strings into a datetime format. There is still some functionality I'd like to add, but I thought I'd share my progress so far to see what you think. A right-click "Format Selection" function with associated popup would be a really neat addition, in addition I'd like to build some better functionality for `time` and `timedelta` formatters. 

## Example Code:
```
from tksheet import *
import tkinter as tk

class demo(tk.Tk):
    def __init__(self):
        tk.Tk.__init__(self)
        self.grid_columnconfigure(0, weight = 1)
        self.grid_rowconfigure(0, weight = 1)
        self.frame = tk.Frame(self)
        self.frame.grid_columnconfigure(0, weight = 1)
        self.frame.grid_rowconfigure(0, weight = 1)
        self.sheet = Sheet(self.frame,
                           data = [[f"{r}"]*10 for r in range(20)]
                           )
        self.sheet.enable_bindings()
        self.frame.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.grid(row = 0, column = 0, sticky = "nswe")
        self.sheet.headers(['Nullable Float Cell\n1 decimals places', 
                            'Float Cell', 
                            'Int Cell', 
                            'Bool Cell', 
                            'Percentage Cell\n0 decimal places', 
                            'Datetime Cell', 
                            'Date Cell\nCustom format', 
                            'Time Cell', 
                            'Dropdown Over Nullable\nPercentage Cell', 
                            'Checkboxes always\noverride formatting'])
        
        # ---------- Some examples of cell formatting --------
        self.sheet.format_cells('all', 0, NullableFloatCell, dict(decimals=1))  
        self.sheet.format_cells('all', 1, FloatCell, dict(decimals=5))
        self.sheet.format_cells('all', 2, IntCell)
        self.sheet.format_cells('all', 3, BoolCell)
        self.sheet.format_cells('all', 4, PercentageCell, dict(decimals=0))
        self.sheet.format_cells('all', 5, DatetimeCell)
        self.sheet.format_cells('all', 6, DateCell, dict(format='%d-%m-%Y')) # Custom display format
        self.sheet.format_cells('all', 7, TimeCell)
        self.sheet.create_dropdown('all', 8, values=['', '104%',.24,"300%",'not a number'], set_value=1)
        self.sheet.format_cells('all', 8, NullablePercentageCell)
        self.sheet.format_cells('all', 9, NullablePercentageCell)
        self.sheet.create_checkbox('all', 9, text='Checkbox') # Check boxes always override formatters

        # ---------------- retrieving data -------------------
        print(self.sheet.get_sheet_data()) # Default behaviour, returns converted datatypes
        print(self.sheet.get_sheet_data(get_formatters=True)) # Returns the actual MT.data object with formatter objects in place

app = demo()
app.mainloop()
```

### CODE REVIEW

**Comment by ragardner** [comment]
Thanks for your work and explaining it so well, it is implemented really well I think. I have a few issues which make me reluctant to merge it though and would rather it be a fork

The first is that I don't want the extra imports of dateutil (especially) and (maybe?) datetime, I dont think datetime is a huge deal really though. This is because I originally made this widget for my own purposes and wanted it to run without installing other libraries and be as light weight as possible. But I also generally don't want extra requirements and licenses

I think if people were to opt out of it by setting a startup arg or something (not sure if this is possible) but still use pyinstaller for example they would have to put dateutil in the excludes if they didn't want it

I'm currently using tksheet for a project of my own and complicating maintenance a bit with these changes and possible future additions of my own or other peoples is not something I really want to think about, maybe I'm ocd

I probably should have stated this in a contributions section or something - I will have to write one, but I'm very new to this stuff and don't have consistent time to dedicate to it and long periods where I have no time at all for it

**Comment by CalJaDav** [comment]
Fair enough, this was just some stuff I had added for my own purposes. I am using tksheet for database operations, but I needed some inputs to be strictly typed otherwise they'd cause issues and general frustration from my colleagues at work.  It seemed like this would be useful for someone else down the line, hence the pull request. Totally ok if it is something you'd rather not include. 

re: dateutil, yeah, to be honest, I totally forgot that it wasn't a built-in module. Had I remembered; I probably wouldn't have included it. If these features are something you do decide to include, this module can probably be removed and a (stightly crappier) homebuilt datetime parser be used in its place. Or we can just remove those formatters altogether and include in the docs some examples of how to design your own cell formatters from the abstract base class. I'm happy to do either of these at some point if you think that these features are something you'd like to include in tksheet.

**Comment by ragardner** [comment]
Sorry for the delay in getting back to you,

I think this is something I would be interested in including in tksheet. The flexibility of the extra args in the formatter and the fact it's just in cell options and doesn't otherwise interfere with the table are major plus points, i don't think any other way of doing such a thing would be as good

It's frustrating that, if I'm reading [this right](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat), it was only changed in python 3.11 to accept multiple date formats? and only existed in 3.7 and even then only supported one format?

**Comment by CalJaDav** [comment]
Yeah, it seems like a major oversight and a super easy feature they could implement. If you are interested in implementing my formatters, here is what I suggest I do:
1). Remove the date/time formatters dependent on dateutil. 
2). I'll implement a generic formatter class that a user can use to create cell formatters for any datatype they like. The user will need to provide a converter function and a target datatype. Optionally they can specify whether the formatter is Nullable, a __str__ function and a value it uses for invalid data (this will also let the user use np.nan or pd.NaT which are objectively better options for missing datapoints than a string saying "NA"). 
3). Write this up in the documentation with a few examples of common formatters that people can copy (including the datetime classes). 

Let me know and I'll have a new pull request in a few days with the above changes. Additionally, I'll also open another thread on another feature I'd like to implement that I could use some feedback on.

**Comment by ragardner** [comment]
I think that sounds good but no rush, it might take me some time to test it out and merge it, I've never used abstract base classes before so I have to do some reading

**Pull request closed without merging**
